// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHndDEEactHewNTdHqRtd7umfkwMvG4wU',
    appId: '1:89922806233:web:bc1492952bdff49a4279c8',
    messagingSenderId: '89922806233',
    projectId: 'tiny-trail-f56ec',
    authDomain: 'tiny-trail-f56ec.firebaseapp.com',
    storageBucket: 'tiny-trail-f56ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk4k7Rt3eFoq7dSTdBd6MGRPLXK5eVXSs',
    appId: '1:89922806233:android:44cc5d22c82405414279c8',
    messagingSenderId: '89922806233',
    projectId: 'tiny-trail-f56ec',
    storageBucket: 'tiny-trail-f56ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCprKjYSo7EzBJGXlck20cwHL4OPfrs-Bs',
    appId: '1:89922806233:ios:00323ae3a01459644279c8',
    messagingSenderId: '89922806233',
    projectId: 'tiny-trail-f56ec',
    storageBucket: 'tiny-trail-f56ec.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCprKjYSo7EzBJGXlck20cwHL4OPfrs-Bs',
    appId: '1:89922806233:ios:00323ae3a01459644279c8',
    messagingSenderId: '89922806233',
    projectId: 'tiny-trail-f56ec',
    storageBucket: 'tiny-trail-f56ec.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHndDEEactHewNTdHqRtd7umfkwMvG4wU',
    appId: '1:89922806233:web:10e297ad802a77614279c8',
    messagingSenderId: '89922806233',
    projectId: 'tiny-trail-f56ec',
    authDomain: 'tiny-trail-f56ec.firebaseapp.com',
    storageBucket: 'tiny-trail-f56ec.firebasestorage.app',
  );
}
