#!/usr/bin/env node
/**
 * ============================================================================
 * KAARTECH PPT GENERATOR — MCP SERVER
 * ============================================================================
 * This MCP server exposes the PPT Generator to Claude Desktop so you can
 * say: "Generate a PPT for the 7 SAP Portals" and Claude will call this
 * server to produce the .pptx file.
 *
 * Tools exposed:
 *   1. generate_ppt          — Gemini AI generates content + builds .pptx
 *   2. generate_ppt_from_json — Build .pptx from pre-existing JSON content
 *   3. list_output_files      — List all generated .pptx files
 *   4. get_content_schema     — Return the JSON schema Gemini must follow
 *   5. preview_slide_count    — Count how many slides would be generated
 *   6. inspect_pptx           — Inspect slide structure of any .pptx
 *   7. edit_pptx              — Apply edit operations to a .pptx
 *
 * Setup:
 *   cd PPT_Generator/mcp
 *   npm install
 *   node server.js
 *
 * Claude Desktop config (claude_desktop_config.json):
 * {
 *   "mcpServers": {
 *     "kaartech-ppt": {
 *       "command": "node",
 *       "args": ["<path-to>/PPT_Generator/mcp/server.js"],
 *       "env": {
 *         "GEMINI_API_KEY": "YOUR_KEY_HERE"
 *       }
 *     }
 *   }
 * }
 * ============================================================================
 */

const { McpServer } = require("@modelcontextprotocol/sdk/server/mcp.js");
const { StdioServerTransport } = require("@modelcontextprotocol/sdk/server/stdio.js");
const { z } = require("zod");
const { spawn } = require("child_process");
const path = require("path");
const fs = require("fs");

// ── Paths (Windows-style, forward slashes also work) ──────────────────────
const BASE_DIR = path.resolve(__dirname, "..");
const SRC_DIR = path.join(BASE_DIR, "src");
const OUTPUT_DIR = path.join(BASE_DIR, "output");
const GENERATOR = path.join(SRC_DIR, "ppt_generator.py");
const EDITOR = path.join(SRC_DIR, "ppt_editor.py");
const ENV_FILE = path.join(BASE_DIR, ".env");

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

// ── Read Gemini API key from env or .env file ──────────────────────────────
function getGeminiKey() {
  if (process.env.GEMINI_API_KEY) return process.env.GEMINI_API_KEY;
  if (fs.existsSync(ENV_FILE)) {
    const lines = fs.readFileSync(ENV_FILE, "utf-8").split("\n");
    for (const line of lines) {
      const m = line.match(/^GEMINI_API_KEY\s*=\s*(.+)$/);
      if (m) return m[1].trim().replace(/^["']|["']$/g, "");
    }
  }
  return null;
}

// ── Python runner ─────────────────────────────────────────────────────────
function runPython(scriptPath, args, env = {}) {
  return new Promise((resolve, reject) => {
    const merged = {
      ...process.env,
      GEMINI_API_KEY: getGeminiKey() || "",
      ...env,
    };
    // Windows: use "python", Linux/Mac: use "python3"
    const py = process.platform === "win32" ? "python" : "python3";
    const child = spawn(py, [scriptPath, ...args], {
      env: merged,
      cwd: SRC_DIR,
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (d) => (stdout += d.toString()));
    child.stderr.on("data", (d) => (stderr += d.toString()));

    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout, stderr, code });
      } else {
        reject(new Error(`Python exited ${code}:\n${stderr}\n${stdout}`));
      }
    });

    child.on("error", reject);
  });
}

// ── Content Schema (for get_content_schema tool) ─────────────────────────
const CONTENT_SCHEMA_SUMMARY = `
JSON Schema for PPT content (passed to --json-file or generated by Gemini):
{
  "presentation_title": "string",
  "subtitle": "string",
  "presenter_name": "string",
  "presenter_id": "string",
  "batch": "string",
  "date": "string",
  "agenda": ["item1", "item2", ...],
  "sections": [
    {
      "section_title": "string",
      "section_subtitle": "string",
      "slides": [
        {
          "slide_type": "overview|process|components|dashboard|table|cycle",
          "title": "string",
          "overview_text": "string",
          "sap_module": "string",
          "sap_module_description": "string",
          "key_features": ["..."],
          "business_benefits": ["..."],
          "process_steps": [{"step": "string", "description": "string"}],
          "components": [{"name": "string", "description": "string", "tables": "string"}],
          "dashboard_items": [{"name": "string", "description": "string", "tables": "string"}],
          "table_data": {"headers": [...], "rows": [[...]]}
        }
      ]
    }
  ],
  "thank_you": {"message": "string", "contact": "string"}
}
`;

// ═════════════════════════════════════════════════════════════════════════════
//  MCP SERVER DEFINITION
// ═════════════════════════════════════════════════════════════════════════════

const server = new McpServer({
  name: "kaartech-ppt-generator",
  version: "2.0.0",
});

// ── Tool 1: generate_ppt ─────────────────────────────────────────────────
server.tool(
  "generate_ppt",
  "Generate a KaarTech branded PowerPoint presentation using Gemini AI to create content from a topic or detailed instructions. The presentation will follow the official KaarTech Corporate Template (2024) with title slides, section dividers, content slides, and a thank-you slide.",
  {
    topic: z.string().describe(
      "The topic or detailed instructions for the presentation. " +
      "Example: 'Generate a presentation for 7 SAP Enterprise Portals: Customer, Vendor, Employee, Maintenance, Shop Floor, EHSM, and Quality. Include business cycle mapping, SAP module integration, key features, and dashboard components.'"
    ),
    output_filename: z.string().optional().describe(
      "Optional output filename without extension. Default: auto-generated from title."
    ),
    context: z.string().optional().describe(
      "Additional context such as presenter name, audience, or specific requirements."
    ),
    api_key: z.string().optional().describe(
      "Gemini API key (optional — reads from .env if not provided)."
    ),
  },
  async ({ topic, output_filename, context, api_key }) => {
    const args = ["--topic", topic];
    if (output_filename) args.push("--output", `${output_filename}.pptx`);
    if (context) args.push("--context", context);
    if (api_key) args.push("--api-key", api_key);

    try {
      const result = await runPython(GENERATOR, args);
      const lines = result.stdout.split("\n");
      const doneLine = lines.find((l) => l.includes("[Done] Saved to:"));
      const outPath = doneLine ? doneLine.replace("[Done] Saved to:", "").trim() : "unknown";

      return {
        content: [
          {
            type: "text",
            text:
              `✅ Presentation generated successfully!\n\n` +
              `📁 File: ${outPath}\n\n` +
              `📊 Log:\n${result.stdout}`,
          },
        ],
      };
    } catch (err) {
      return {
        content: [
          {
            type: "text",
            text: `❌ Generation failed:\n\n${err.message}`,
          },
        ],
        isError: true,
      };
    }
  }
);

// ── Tool 2: generate_ppt_from_json ───────────────────────────────────────
server.tool(
  "generate_ppt_from_json",
  "Build a KaarTech PowerPoint from a pre-structured JSON content object. Use this when you have already structured the slide content and want to skip the Gemini AI step.",
  {
    content_json: z.string().describe(
      "JSON string matching the KaarTech PPT content schema. Must include presentation_title, sections, agenda, and thank_you."
    ),
    output_filename: z.string().optional().describe(
      "Output filename without extension."
    ),
  },
  async ({ content_json, output_filename }) => {
    // Write JSON to temp file
    const tmpFile = path.join(OUTPUT_DIR, "_tmp_content.json");
    try {
      JSON.parse(content_json); // validate
      fs.writeFileSync(tmpFile, content_json, "utf-8");
    } catch (e) {
      return {
        content: [{ type: "text", text: `❌ Invalid JSON: ${e.message}` }],
        isError: true,
      };
    }

    const args = ["--json-file", tmpFile];
    if (output_filename) args.push("--output", `${output_filename}.pptx`);

    try {
      const result = await runPython(GENERATOR, args);
      const lines = result.stdout.split("\n");
      const doneLine = lines.find((l) => l.includes("[Done] Saved to:"));
      const outPath = doneLine ? doneLine.replace("[Done] Saved to:", "").trim() : tmpFile;

      fs.unlinkSync(tmpFile); // cleanup

      return {
        content: [
          {
            type: "text",
            text:
              `✅ Presentation built from JSON!\n\n` +
              `📁 File: ${outPath}\n\n` +
              `Log:\n${result.stdout}`,
          },
        ],
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `❌ Build failed:\n\n${err.message}` }],
        isError: true,
      };
    }
  }
);

// ── Tool 3: list_output_files ────────────────────────────────────────────
server.tool(
  "list_output_files",
  "List all PowerPoint files generated by the KaarTech PPT Generator.",
  {},
  async () => {
    if (!fs.existsSync(OUTPUT_DIR)) {
      return {
        content: [{ type: "text", text: "No output directory found. No files generated yet." }],
      };
    }
    const files = fs.readdirSync(OUTPUT_DIR).filter((f) => f.endsWith(".pptx"));
    if (files.length === 0) {
      return {
        content: [{ type: "text", text: "No .pptx files generated yet." }],
      };
    }
    const list = files
      .map((f) => {
        const full = path.join(OUTPUT_DIR, f);
        const stat = fs.statSync(full);
        const kb = (stat.size / 1024).toFixed(1);
        const modified = stat.mtime.toLocaleString();
        return `📄 ${f}  (${kb} KB, modified: ${modified})`;
      })
      .join("\n");
    return {
      content: [
        {
          type: "text",
          text: `Generated presentations in ${OUTPUT_DIR}:\n\n${list}`,
        },
      ],
    };
  }
);

// ── Tool 4: get_content_schema ───────────────────────────────────────────
server.tool(
  "get_content_schema",
  "Return the JSON schema that the KaarTech PPT Generator expects. Use this to understand the structure before passing JSON to generate_ppt_from_json.",
  {},
  async () => ({
    content: [{ type: "text", text: CONTENT_SCHEMA_SUMMARY }],
  })
);

// ── Tool 5: preview_slide_count ──────────────────────────────────────────
server.tool(
  "preview_slide_count",
  "Given a content JSON string, estimate how many slides the generated presentation would contain.",
  {
    content_json: z.string().describe("JSON content string matching the PPT schema."),
  },
  async ({ content_json }) => {
    try {
      const c = JSON.parse(content_json);
      let count = 2; // cover + agenda
      for (const sec of c.sections || []) {
        count += 1; // section divider
        count += (sec.slides || []).length;
      }
      count += 1; // thank you
      return {
        content: [
          {
            type: "text",
            text: `Estimated slide count: ${count}\n  • 1 cover\n  • 1 agenda\n  • ${c.sections?.length || 0} section dividers\n  • ${count - 3 - (c.sections?.length || 0)} content slides\n  • 1 thank-you`,
          },
        ],
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `❌ Invalid JSON: ${e.message}` }],
        isError: true,
      };
    }
  }
);

// ── Tool 6: inspect_pptx ─────────────────────────────────────────────────
server.tool(
  "inspect_pptx",
  "Inspect an existing PowerPoint file and return its complete slide structure: slide count, layout names, shape names, and text content. Use this FIRST before editing a file so you know exactly what's in it.",
  {
    file_path: z.string().describe(
      "Full path to the .pptx file to inspect. " +
      "For files in the output folder, use the filename only (e.g. 'THISO_L2_Portal.pptx'). " +
      "For files elsewhere, provide the full path."
    ),
  },
  async ({ file_path }) => {
    // Resolve path: if no directory separator, look in output dir
    let resolvedPath = file_path.includes("\\") || file_path.includes("/")
      ? file_path
      : path.join(OUTPUT_DIR, file_path);

    if (!fs.existsSync(resolvedPath)) {
      // Also check user's common locations
      const alternatives = [
        path.join(OUTPUT_DIR, file_path),
        path.join(BASE_DIR, "reference", file_path),
        file_path,
      ];
      const found = alternatives.find((p) => fs.existsSync(p));
      if (!found) {
        return {
          content: [
            {
              type: "text",
              text: `❌ File not found: ${file_path}\nLooked in:\n${alternatives.join("\n")}`,
            },
          ],
          isError: true,
        };
      }
      resolvedPath = found;
    }

    const args = ["inspect", "--file", resolvedPath];
    try {
      const result = await runPython(EDITOR, args);
      // Also load the JSON structure if saved
      const jsonPath = path.join(OUTPUT_DIR, "inspected_structure.json");
      let structureJson = null;
      if (fs.existsSync(jsonPath)) {
        structureJson = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
      }
      return {
        content: [
          {
            type: "text",
            text: structureJson
              ? `✅ Inspection complete!\n\n📊 File: ${structureJson.file}\n📑 Total slides: ${structureJson.total_slides}\n\n` +
                structureJson.slides
                  .map(
                    (s) =>
                      `Slide ${s.slide_number}: [${s.layout_name}]\n` +
                      s.shapes
                        .filter((sh) => sh.has_text)
                        .map((sh) => `  • ${sh.name}: ${sh.text_preview}`)
                        .join("\n")
                  )
                  .join("\n\n")
              : result.stdout,
          },
        ],
      };
    } catch (err) {
      return {
        content: [
          { type: "text", text: `❌ Inspection failed:\n${err.message}` },
        ],
        isError: true,
      };
    }
  }
);

// ── Tool 7: edit_pptx ────────────────────────────────────────────────────
server.tool(
  "edit_pptx",
  "Edit an existing PowerPoint file by applying a list of operations (title, section, text, replace, replace_all, append, add_slide, font_slide, delete_slide). The original file is NEVER modified — a new edited copy is saved to the output folder. Use inspect_pptx first to understand the file structure.",
  {
    file_path: z.string().describe(
      "Full path to the existing .pptx file to edit, OR just filename if it's in the output folder."
    ),
    output_filename: z.string().optional().describe(
      "Output filename for the edited copy (without path). Defaults to 'edited_<original_name>.pptx'."
    ),
    edits: z
      .array(
        z.object({
          op: z
            .enum([
              "title",
              "section",
              "text",
              "replace",
              "replace_all",
              "append",
              "add_slide",
              "font_slide",
              "delete_slide",
            ])
            .describe("The type of edit operation to perform"),
          slide: z
            .number()
            .optional()
            .describe("1-based slide number to edit"),
          after: z
            .number()
            .optional()
            .describe("Slide number to insert the new slide after (0 to prepend)"),
          shape: z
            .string()
            .optional()
            .describe("Name of the shape to edit (partial match ok)"),
          ph: z
            .number()
            .optional()
            .describe("Placeholder index to edit (0=title, 1=content, etc.)"),
          text: z
            .string()
            .optional()
            .describe("Text content to set or append"),
          font: z
            .string()
            .optional()
            .describe("Font name, e.g. 'Arial' or 'Calibri'"),
          size: z
            .number()
            .optional()
            .describe("Font size in points"),
          bold: z
            .boolean()
            .optional()
            .describe("Whether text should be bold"),
          color: z
            .string()
            .optional()
            .describe("Text color as 6-char hex without #, e.g. 'C0202B'"),
          find: z
            .string()
            .optional()
            .describe("Text to find for replace operations"),
          replace: z
            .string()
            .optional()
            .describe("Replacement text"),
          layout: z
            .string()
            .optional()
            .describe("Layout name fragment for new slide"),
          title: z
            .string()
            .optional()
            .describe("Title for new slide"),
          body: z
            .string()
            .optional()
            .describe("Body text for new slide"),
        })
      )
      .describe(
        "List of edit operations to apply in order. Example: [{op: 'title', slide: 1, text: 'New Title'}]"
      ),
  },
  async ({ file_path, output_filename, edits }) => {
    // Resolve input path
    const resolvedPath =
      file_path.includes("\\") || file_path.includes("/")
        ? file_path
        : path.join(OUTPUT_DIR, file_path);

    if (!fs.existsSync(resolvedPath)) {
      return {
        content: [
          {
            type: "text",
            text: `❌ File not found: ${resolvedPath}\nTip: Use inspect_pptx first to confirm the file exists.`,
          },
        ],
        isError: true,
      };
    }

    // Write edits to a temp JSON file
    const editsFile = path.join(OUTPUT_DIR, "_tmp_edits.json");
    fs.writeFileSync(editsFile, JSON.stringify(edits, null, 2), "utf-8");

    const outName =
      output_filename || `edited_${path.basename(resolvedPath)}`;
    const args = [
      "edit",
      "--file",
      resolvedPath,
      "--edits",
      editsFile,
      "--output",
      outName,
    ];

    try {
      const result = await runPython(EDITOR, args);
      // Cleanup temp file
      try {
        fs.unlinkSync(editsFile);
      } catch {}

      const outPath = path.join(OUTPUT_DIR, outName);
      const exists = fs.existsSync(outPath);
      const sizeKb = exists
        ? (fs.statSync(outPath).size / 1024).toFixed(1)
        : "?";

      return {
        content: [
          {
            type: "text",
            text:
              `✅ Edits applied successfully!\n\n` +
              `📁 Output: ${outPath}\n` +
              `📦 Size: ${sizeKb} KB\n` +
              `🔧 Operations applied: ${edits.length}\n\n` +
              `Log:\n${result.stdout}`,
          },
        ],
      };
    } catch (err) {
      try {
        fs.unlinkSync(editsFile);
      } catch {}
      return {
        content: [
          { type: "text", text: `❌ Edit failed:\n\n${err.message}` },
        ],
        isError: true,
      };
    }
  }
);

// ── Start the server ──────────────────────────────────────────────────────
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("[KaarTech PPT MCP] Server started on stdio transport.");
  console.error(`[KaarTech PPT MCP] Generator: ${GENERATOR}`);
  console.error(`[KaarTech PPT MCP] Output dir: ${OUTPUT_DIR}`);
  const key = getGeminiKey();
  console.error(`[KaarTech PPT MCP] Gemini API key: ${key ? "✅ found" : "❌ NOT FOUND — set GEMINI_API_KEY in .env"}`);
}

main().catch((err) => {
  console.error("[KaarTech PPT MCP] Fatal error:", err);
  process.exit(1);
});
